name: "Get environment"
description: "Returns the environment in which a calling workflow is running"
inputs:
  ref:
    description: "The git reference (github.ref)"
    required: false
    default: ${{ github.ref }}

runs:
  using: composite
  steps:
    - name: Get environment
      id: get-env
      run: |
        prodregex='^refs\/heads(\/v\d.*)?\/(master|main)$'
        stagingregex='refs\/heads(\/v\d.*)?\/(staging|stage)'
        releaseregex='refs\/heads(\/v\d.*)?\/(release)'

        if [[ "${{ inputs.ref }}" =~ ${prodregex} ]]; then
          echo "::set-output name=environmentname::production"
          echo "Returned production environment!"
        elif [["${{ inputs.ref }}" =~ [^$stagingregex] ]]; then
          echo "::set-output name=environmentname::staging"
          echo "Returned staging environment!"
        elif [["${{ inputs.ref }}" =~ [^$releaseregex] ]]; then
          echo "::set-output name=environmentname::release"
          echo "Returned release environment!"
        else
          echo "::set-output name=environmentname::development"
          echo "Returned development environment!"
        fi
      shell: bash

outputs:
  environmentname:
    description: "The current environment"
    value: ${{ steps.get-env.outputs.environmentname }}
