name: "Get environment"
description: "Returns the environment in which a calling workflow is running"
inputs:
  ref:
    description: "The git reference (github.ref)"
    required: false
    default: ${{ github.ref }}

runs:
  using: 'node16'
  main: 'index.js'

outputs:
  environmentname:
    description: "The current environment"
